config/routes.rb
Demoblog::Application.routes.draw do
  get "admin/index"=>"admin#index"

  get "error"=>'error#show'

  get "essearch/search"
  get "essearch/bulkindex"

  devise_for :users
  resources :posts

  resources :categories
  resources :admin
  resources :comments
  resources :tags
  get "/comments/new/:parent_id"=>"comments#new"

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :comment,:post_id,:parent_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:index,:new, :create,:edit, :update,:destroy]
  before_filter :check_role_autorization

  before_filter :set_comment, only: [:edit, :update, :destroy]
  before_filter :set_comment_for_show, only: [:show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    if params[:parent_id]!=nil
      @ParentComment = Comment.find(params[:parent_id])
      @comment.parent_id=@ParentComment.id
      @comment.post_id=@ParentComment.post_id
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id=current_user.id


    respond_to do |format|
      if @comment.save
        #UserMailer.send_comment_mail(@comment.user.email,@comment.post_id).deliver
        SendCommentMailWorker.perform_async(@comment.user.email,@comment.post_id)
        format.html { redirect_to '/posts/'+@comment.post_id.to_s, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end

    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to '/posts/'+@comment.post_id.to_s }
      format.json { head :no_content }
    end
  end
  private

  def set_comment

    @comment = Comment.where(:id => params[:id],:user_id=>current_user.id).first
    #abort @post.inspect
  end
  def set_comment_for_show
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.hidden_field :post_id %>
    <%= f.hidden_field :parent_id %>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_field :comment %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_hcomments.html.erb
<style>
  article, article article {
    margin-left: 48px;

    margin-bottom: 10px;

  }
    </style>
<%=  @commentTreeHtml.html_safe %>

app/views/comments/edit.html.erb
<h4>Editing comment</h4>

<%= render 'comment' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h4>Listing comments</h4>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h4>New comment</h4>

<%= render 'comment' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>