config/routes.rb
Demoblog::Application.routes.draw do
  get "admin/index"=>"admin#index"

  get "error"=>'error#show'

  get "essearch/search"
  get "essearch/bulkindex"

  devise_for :users
  resources :posts

  resources :categories
  resources :admin
  resources :comments
  resources :tags
  get "/comments/new/:parent_id"=>"comments#new"

  root :to => 'posts#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :post_count,:user_id
  has_and_belongs_to_many :posts
  validates :name, :uniqueness => {:scope => :name}

  validates_length_of :name, :minimum => 1, :maximum => 20

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!, only: [:index,:new, :create,:edit, :update,:destroy]
  before_filter :check_role_autorization

  before_filter :set_tag, only: [:edit, :update, :destroy]
  before_filter :set_tag_for_show, only: [:show]
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])
    @tag.user_id=current_user.id
    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
  private

  def set_tag

    @tag = Tag.where(:id => params[:id],:user_id=>current_user.id).first
    #abort @post.inspect
  end
  def set_tag_for_show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h4>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h4>Editing tag</h4>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h4>Listing tags</h4>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to tag.name, tag %></td>

    <!--<td><%#=  tag.post_count||0%></td>-->

    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h4>New tag</h4>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>