config/routes.rb
Demoblog::Application.routes.draw do
  get "admin/index"=>"admin#index"

  get "error"=>'error#show'

  get "essearch/search"
  get "essearch/bulkindex"

  devise_for :users
  resources :posts

  resources :categories
  resources :admin
  resources :comments
  resources :tags
  get "/comments/new/:parent_id"=>"comments#new"

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  attr_accessible :comment_count, :content,:tags, :title,:user_id,:category_id
  validates :content, :title, presence: true
  validates_length_of :title, :minimum => 1, :maximum => 255
  validates_length_of :content, :minimum => 1, :maximum => 5000
  validates :category_id, presence: true
  has_and_belongs_to_many :tags
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'elasticsearch/es_client'
  before_filter :authenticate_user!, only: [:index,:new, :create,:edit, :update,:destroy]
  before_filter :check_role_autorization

  before_filter :set_post, only: [:edit, :update, :destroy]
  before_filter :set_post_for_show, only: [:show]
  before_filter :prepare_categories
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    #abort @post.comments.inspect
    if @post.comments!=nil
    @comment_tree= build_commentree(@post.comments.as_json)
    @commentTreeHtml=build_commentreeHtml(@comment_tree)

   end
    @comment=Comment.new
    @comment.post_id=@post.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])


  end

  # POST /posts
  # POST /posts.json
  def create
    #abort params[:post].inspect

    @tag=Tag.where(id:params[:post]['tags'])
    params[:post]['tags']=@tag

    @post = Post.new(params[:post])
    @post.user_id=current_user.id
    ES_Index()
#abort @post.inspect
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update

    @tag=Tag.where(id:params[:post]['tags'])
    params[:post]['tags']=@tag
    @post = Post.find(params[:id])
    ES_Index()
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    ES_Index_Delete()
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  private
  def ES_Index
    @ES_PostClient=ES_PostClient.new
    @ES_PostClient.index("sting", @post.id, @post )
  end
  def ES_Index_Delete
    begin
      @ES_PostClient=ES_PostClient.new
      @ES_PostClient.delete("sting",@post.id)
    rescue
    end
  end
  def set_post

    @post = Post.where(:id => params[:id],:user_id=>current_user.id).first
    #abort @post.inspect
  end
  def set_post_for_show
    @post = Post.find(params[:id])
  end

  def prepare_categories
    @categories = Category.order(:name)
  end
  def build_commentree(elements, parentId=nil)
    tree = Array.new
    elements.each do |element|

      if element['parent_id'] == parentId
        #abort element['id'].inspect
        element['username']=Comment.find(element['id']).user.email
        children = build_commentree(elements, element['id'])
        #abort children.inspect
        if children.any?

          element['children']=children
          #element.store(children: children)
          #element.merge('children'=>children)
          # abort element.inspect
        end

        tree.push(element)

      end
    end

    return tree

  end
  #will move in view healper
  def build_commentreeHtml(commentTree)
     #abort commentTree.inspect
    htmlTree = "<article>"
    commentTree.each do |comment|
      htmlTree+="<header><p>PostedBy:"+comment["username"].to_s+"</p><p>PostedAt:"+comment["created_at"].to_s+"</p></header>"
      htmlTree+="<p>"+comment["comment"]+"</p>"

      htmlTree+="<a href='/comments/new/"+comment['id'].to_s+"'>Reply</a>"
      if current_user.id==comment['user_id']
        htmlTree+="|<a href='/comments/"+comment['id'].to_s+"' data-method='delete'>Delete</a>"
      end
        htmlTree+="<hr/>"
      if comment["children"]
        #abort comment["children"].inspect
        htmlTree+= build_commentreeHtml(comment["children"])

      end


    end
    #abort htmlTree.inspect
    htmlTree+="</article>"

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :category_id %><br />
      <% #abort @post.tags.inspect%>

      <%= f.collection_select(:category_id, @categories, :id, :name, {:include_blank => "Please select"}) %>
      <%#= f.collection_select(:category_id, @categories, :id, :name, {:include_blank => "Please select"}, {:class=>'input-field'}) %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <div class="field">

      <%# Tag::AS.each do |a_value| %>
          <%#= f.check_box(:a, { :multiple => true }, a_value) %>
      <%# end %>
      <%= f.select(:tags,options_from_collection_for_select(Tag.all, 'id', 'name',@post.tags.collect { |x| x.id }) ,{},:multiple => true)%>
      <%#= f.select(:tags,Tag.all.collect {|x| [x.name, x.id]} ,{},:multiple => true)%>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h4>Editing post</h4>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h4>Listing posts</h4>



<% @posts.each do |post| %>
 <div >
<h5><%= link_to post.title, post %></h5>
<ul class="list-inline">
  <li>Posted At:<%= post.created_at.strftime("%Y-%m-%d")%></li>
  <li>Tags:<% post.tags.each do|tag|%>
        <%= tag.name%>&nbsp;
    <% end%></li>
    <!--<li>Comment(<%#= post.comment_count||0 %>)</li>-->
    <li>Author: <%=  post.user.email %></li>
  <% if current_user.id==post.user_id %>
  <li>
  <%=link_to 'Edit', edit_post_path(post) %>

        </li>

  <li><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <%end%>
  </ul>

  </div>
    <hr/>
<% end %>


<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h4>New post</h4>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <b>User:</b>
  <%= @post.user.email %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<p>
  <b>Tags:</b>
  <% @post.tags.each do|tag|%>
  <%= tag.name %>
  <% end%>
</p>
<% if current_user.id==@post.user_id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
    <% end%>
<h5>Comments</h5>
<% #abort @comment_tree.inspect%>
<%= render :partial =>"comments/hcomments",locals: {commentTreeHtml: @commentTreeHtml} %>

<h5>New comment</h5>
<%#= render partial:"new", collection: @post %>

<%= render :partial =>"comments/comment",locals: {comment: @comment} %>

<%= link_to 'Back', comments_path %>