config/routes.rb
Demoblog::Application.routes.draw do
  get "admin/index"=>"admin#index"

  get "error"=>'error#show'

  get "essearch/search"
  get "essearch/bulkindex"

  devise_for :users
  resources :posts

  resources :categories
  resources :admin
  resources :comments
  resources :tags
  get "/comments/new/:parent_id"=>"comments#new"

  root :to => 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  attr_accessible :name, :post_count, :slug,:user_id
  belongs_to :user
  has_many :posts
  validates :name, :uniqueness => {:scope => :name}
  validates :slug, :uniqueness => {:scope => :slug}
  validates_length_of :name, :minimum => 1, :maximum => 20
  validates_length_of :slug, :minimum => 1, :maximum => 20
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, only: [:index,:new, :create,:edit, :update,:destroy]
  before_filter :check_role_autorization

  before_filter :set_cat, only: [:edit, :update, :destroy]
  before_filter :set_cat_for_show, only: [:show]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    @category.user_id=current_user.id
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
  private

  def set_cat

    @category = Category.where(:id => params[:id],:user_id=>current_user.id).first
    #abort @post.inspect
  end
  def set_cat_for_show
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :slug %><br />
      <%= f.text_field :slug %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h4>Editing category</h4>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h4>Listing categories</h4>

<table>
  <tr>

    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, category %></td>
    <td><%=  category.slug %></td>
    <td><%=  category.post_count||0%></td>

    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h4>New category</h4>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Slug:</b>
  <%= @category.slug %>
</p>




<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>